const WORDS=(window.SHICI_WORD_ROWS||[]).map((w,i)=>({id:i+1,word:w[0],phonetic:w[1],pos:w[2],meaning:w[3],collocation:w[4],example:w[5],topic:w[6]}));
const READINGS=[
  {id:'attention',title:'The Cost of Constant Connection',level:'六级阅读 · 社会生活',minutes:8,targets:['substantial','prevalent','undermine','empirical','facilitate','vulnerable','incentive','coherent'],paragraphs:[
    `Digital tools facilitate communication, but the expectation of constant availability has created a less visible cost. Notifications are now so prevalent that many people check their phones without making a conscious decision. Each interruption may appear trivial, yet the accumulated effect can be substantial. When attention repeatedly shifts between a demanding task and a message, the mind must reconstruct what it was doing. This transition consumes time and may undermine both accuracy and creativity.`,
    `The problem is not simply a lack of discipline. Empirical research suggests that even the presence of a silent phone can reduce available mental capacity, especially when a person is waiting for important news. People who are already tired or anxious may be particularly vulnerable to this effect. Yet many digital services have an incentive to maximize the time users spend checking them.`,
    `A coherent response therefore requires more than turning off every device. Researchers recommend creating periods of protected attention, keeping distracting devices out of reach, and deciding in advance when messages will be checked. The goal is not to reject technology, but to use it deliberately rather than automatically.`],questions:[
      {q:'What is the main idea of the passage?',options:['Digital tools should be removed from workplaces.','Constant digital interruption carries cognitive costs that require deliberate management.','Phone users lack the discipline needed for demanding work.','Silent phones are more distracting than active ones.'],answer:1,why:'全文先说明持续打断的认知成本，再提出有意识地管理注意力。'},
      {q:'Why does switching attention reduce performance?',options:['People forget how to operate their devices.','Messages are usually inaccurate.','The mind must rebuild the context of the interrupted task.','Creative tasks require complete silence.'],answer:2,why:'第一段指出，每次切换后大脑都要重新构建原任务的上下文。'},
      {q:'What does the author recommend?',options:['Checking messages at planned times.','Replying to every important message immediately.','Using more productivity applications.','Keeping a silent phone on the desk.'],answer:0,why:'末段明确建议预先决定查看消息的时间，并设置受保护的专注时段。'}]},
  {id:'green-cities',title:'Why Small Green Spaces Matter',level:'六级阅读 · 城市发展',minutes:8,targets:['urbanization','infrastructure','ecological','conservation','well-being','allocate','sustainable','community'],paragraphs:[
    `Rapid urbanization has often treated parks as pleasant extras rather than essential infrastructure. Yet a growing body of research indicates that even small green spaces can improve physical health, reduce summer temperatures and support psychological well-being. Their value is especially high in crowded districts where residents have limited access to private gardens.`,
    `Large parks remain important, but they are not the only sustainable option. Cities can transform unused corners, school grounds and the edges of transport routes into small ecological networks. When these spaces are connected, birds and insects can move between them, strengthening urban conservation efforts. Local trees also provide shade where heat is most intense.`,
    `The difficult question is how to allocate limited land. A successful plan depends on community knowledge: residents often know which walking routes lack shade and which neglected spaces feel unsafe. By combining scientific evidence with local experience, city planners can create green spaces that are both environmentally useful and genuinely used.`],questions:[
      {q:'What assumption does the passage challenge?',options:['Parks are difficult to maintain.','Only large parks can benefit urban residents.','Residents prefer private gardens.','Cities should stop building transport routes.'],answer:1,why:'文章强调小型绿地同样能够改善健康、降温并形成生态网络。'},
      {q:'How can small green spaces support conservation?',options:['By replacing all school grounds.','By attracting private investment.','By forming connected routes for wildlife.','By reducing the number of residents.'],answer:2,why:'第二段说明，相互连接的小型绿地能让鸟类和昆虫在其间移动。'},
      {q:'Why should residents participate in planning?',options:['They understand how local spaces are actually used.','They can provide free construction labor.','They own most unused city land.','They prefer plans without scientific evidence.'],answer:0,why:'末段指出，居民掌握遮阴不足、空间安全等实际使用信息。'}]},
  {id:'choice',title:'When More Choice Becomes a Burden',level:'六级阅读 · 心理与消费',minutes:8,targets:['paradox','incentive','ambiguous','contemplate','prevalent','adverse','scrutinize','perspective'],paragraphs:[
    `Modern consumers are offered an unprecedented range of products, services and subscription plans. In theory, greater choice should make it easier to find an ideal match. In practice, it can create a paradox: the more options people receive, the less confident they may feel about any decision. This response is particularly prevalent when differences between products are ambiguous.`,
    `Consumers may spend hours scrutinizing minor details and contemplating what they might lose by selecting one option over another. Even after making a purchase, they can imagine that an unchosen alternative would have been better. Such comparisons may have an adverse effect on satisfaction, regardless of the product’s actual quality. Sellers, meanwhile, have an incentive to present many plans because a broad range can signal expertise.`,
    `From a practical perspective, people can reduce the burden by deciding which two or three qualities truly matter before they compare options. A limited set of criteria does not guarantee a perfect choice, but it turns an exhausting search into a manageable decision.`],questions:[
      {q:'What is the paradox described in the passage?',options:['Cheaper products often have better quality.','More options can make people less satisfied with their decisions.','Consumers rarely compare subscription plans.','Sellers prefer to offer fewer products.'],answer:1,why:'首段指出，选择越多，人们反而可能越不确定。'},
      {q:'Why may sellers offer many plans?',options:['To prevent consumers from comparing details.','To reduce the quality of each plan.','Because variety can make them appear knowledgeable.','Because consumers always select the cheapest one.'],answer:2,why:'第二段说，广泛的选项可以传递专业度。'},
      {q:'What solution does the author suggest?',options:['Avoiding all major purchases.','Selecting a few important criteria in advance.','Always choosing the most popular option.','Reading every available review.'],answer:1,why:'末段建议在比较前先确定两三个真正重要的标准。'}]},
  {id:'remote-work',title:'The Uneven Geography of Remote Work',level:'六级阅读 · 职场',minutes:8,targets:['commute','facilitate','constraint','undermine','consensus','implement','mandatory','resilient'],paragraphs:[
    `Remote work can eliminate a long commute and facilitate cooperation across cities, but its benefits are not distributed equally. A quiet room, reliable internet and control over one’s schedule are resources rather than universal conditions. For employees sharing limited accommodation, space becomes a serious constraint.`,
    `Organizations also face a tension between flexibility and coordination. Mandatory office days may simplify meetings, yet they can undermine the autonomy that makes remote work attractive. There is no clear consensus on the ideal number of office days because different tasks require different forms of collaboration.`,
    `More resilient policies therefore focus on outcomes rather than attendance alone. Teams can implement shared hours for quick decisions while protecting uninterrupted time for individual work. Managers must also examine whether remote employees receive the same access to information and promotion. Flexibility works best when it is supported by explicit rules, not informal privilege.`],questions:[
      {q:'Why are the benefits of remote work uneven?',options:['All jobs require office equipment.','Workers have different home resources and conditions.','Managers refuse to use the internet.','Employees dislike flexible schedules.'],answer:1,why:'首段指出安静空间、稳定网络和时间控制并非人人都有。'},
      {q:'What problem can mandatory office days create?',options:['They eliminate all meetings.','They make the commute shorter.','They may weaken the autonomy employees value.','They prevent managers from sharing information.'],answer:2,why:'第二段指出，强制到岗可能削弱远程工作的自主性。'},
      {q:'What characterizes a resilient remote-work policy?',options:['Judging work mainly by attendance.','Allowing every worker to choose any schedule.','Combining shared coordination time with protected focus time.','Avoiding explicit rules.'],answer:2,why:'末段建议既设共享时段，又保护个人不受打扰的工作时间。'}]},
  {id:'craft',title:'Keeping Traditional Crafts Alive',level:'六级阅读 · 文化传承',minutes:8,targets:['heritage','craftsmanship','preservation','inherit','revitalize','prosperity','initiative','accessible'],paragraphs:[
    `Traditional craftsmanship is often described as cultural heritage, but preservation does not mean freezing a practice in the past. A craft survives only when a new generation can inherit its knowledge and find a meaningful place for it in contemporary life. Museums can document techniques, yet documentation alone cannot keep a working tradition alive.`,
    `Some towns have launched an initiative to connect experienced artisans with young designers. The aim is not to replace traditional methods, but to make the resulting products more accessible to modern users. New forms and online markets can revitalize local workshops while preserving the skills that give each object its character.`,
    `This approach may also support regional prosperity, but commercial success should not become the only measure of value. Training requires time, materials and patient supervision. If markets reward speed alone, the slow knowledge embodied in craftsmanship may disappear. The strongest programs therefore balance income with long-term learning.`],questions:[
      {q:'Why is documentation alone insufficient?',options:['Museums cannot display traditional objects.','A living craft requires people to continue practicing it.','Young designers reject all traditional methods.','Online markets cannot sell handmade products.'],answer:1,why:'第一段强调，技艺要存续必须有人继续学习与实践。'},
      {q:'What is the purpose of connecting artisans with designers?',options:['To replace traditional methods.','To make crafts relevant to contemporary users.','To move every workshop online.','To reduce the time required for training.'],answer:1,why:'第二段说明，合作旨在让产品更适合当代使用，同时保留核心技艺。'},
      {q:'What risk does the author identify?',options:['Commercial pressure may favor speed over deep learning.','Regional prosperity makes crafts less valuable.','Training uses no physical materials.','Museums provide too much supervision.'],answer:0,why:'末段担心市场只奖励速度，从而让缓慢积累的知识消失。'}]},
  {id:'citizen-science',title:'Can Ordinary People Produce Useful Science?',level:'六级阅读 · 科学研究',minutes:8,targets:['empirical','advocate','qualification','supervise','discrepancy','compelling','initiative','unprecedented'],paragraphs:[
    `Citizen-science projects invite members of the public to collect observations for research. Supporters advocate these projects because thousands of volunteers can cover an area and a period that would be impossible for a small professional team. This scale can produce an unprecedented amount of empirical data.`,
    `Critics question whether participants without formal qualification can record reliable information. A discrepancy may appear when two volunteers classify the same bird or weather event differently. Good projects respond by providing clear examples, testing participants on sample observations and asking specialists to supervise unusual reports.`,
    `The most compelling evidence for citizen science comes from projects that publish both their findings and their error-checking methods. Transparency allows other researchers to judge where volunteer data is strong and where caution is needed. A successful initiative does not pretend that every observation is perfect; it designs a system in which many imperfect observations can still reveal a meaningful pattern.`],questions:[
      {q:'What major advantage does citizen science offer?',options:['It removes the need for professional researchers.','It can collect observations across a very large scale.','It guarantees that every record is accurate.','It gives volunteers formal qualifications.'],answer:1,why:'首段强调，大量志愿者能覆盖专业小团队无法覆盖的范围和时间。'},
      {q:'How can projects improve data reliability?',options:['By hiding uncertain reports.','By accepting only experienced volunteers.','By training participants and reviewing unusual observations.','By avoiding the classification of events.'],answer:2,why:'第二段列出示例训练、样本测试和专家复核异常报告。'},
      {q:'According to the author, what makes a project convincing?',options:['Claiming that all observations are perfect.','Publishing findings without methods.','Being transparent about error-checking.','Collecting less data.'],answer:2,why:'末段把透明公开发现与误差检查方法视为最有说服力的证据。'}]}
];

const INTERVALS=[10,1440,2880,5760,10080,21600,43200],STORAGE_KEY='shici_cet6_v1';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const dayKey=(ts=Date.now())=>{const d=new Date(ts);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const defaultState=()=>({version:2,progress:{},history:[],activeDays:[],daily:{},createdAt:Date.now()});
function loadState(){try{const old=JSON.parse(localStorage.getItem(STORAGE_KEY));return old&&old.progress?{...defaultState(),...old,daily:old.daily||{}}:defaultState()}catch{return defaultState()}}
let state=loadState(),today=dayKey(),daily,passage,readingStart=Date.now(),timerId,roundNo=1,roundQueue=[],wordIndex=0,roundRatings=[],cardFlipped=false,memorySignalled=false,activeTopic='全部',deferredInstall=null;
function pickPassage(){let n=0;for(const c of today)n+=c.charCodeAt(0);return READINGS[n%READINGS.length]}
passage=pickPassage();daily=state.daily[today]||{passageId:passage.id,startedAt:Date.now(),reading:null,rounds:[],summary:null};state.daily[today]=daily;
function save(){state.version=2;localStorage.setItem(STORAGE_KEY,JSON.stringify(state));const pill=$('.sync-pill');if(pill)pill.innerHTML='<i></i>已存于本机'}
function wordByName(name){return WORDS.find(w=>w.word.toLowerCase()===name.toLowerCase())}
function escapeRx(s){return s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}
function formatSeconds(sec){return `${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}
function speak(text){if(!('speechSynthesis'in window)){toast('当前浏览器不支持朗读');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=.9;speechSynthesis.speak(u)}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2300)}

function renderPassage(){
  $('#passageMeta').textContent=`${passage.level} · 建议 ${passage.minutes} 分钟`;
  $('#passageTitle').textContent=passage.title;
  const rx=new RegExp(`\\b(${passage.targets.map(escapeRx).join('|')})\\b`,'gi');
  $('#passageBody').innerHTML=passage.paragraphs.map(p=>`<p>${p.replace(rx,m=>`<button class="vocab-mark" data-word="${m.toLowerCase()}">${m}</button>`)}</p>`).join('');
  $('#passageWords').innerHTML=passage.targets.map(w=>`<span>${w}</span>`).join('');
  $('#questionList').innerHTML=passage.questions.map((q,qi)=>`<section class="question" data-question="${qi}"><p>${qi+1}. ${q.q}</p>${q.options.map((o,oi)=>`<label class="option"><input type="radio" name="q${qi}" value="${oi}"><span>${String.fromCharCode(65+oi)}. ${o}</span></label>`).join('')}<div class="explanation" hidden>${q.why}</div></section>`).join('');
  $$('.vocab-mark').forEach(b=>b.addEventListener('click',e=>showWordPopover(e.currentTarget)));
  $$('#questionList input').forEach(i=>i.addEventListener('change',updateQuestionProgress));
  if(daily.reading)showReadingResult(true);else startReadingTimer();
}
function startReadingTimer(){clearInterval(timerId);timerId=setInterval(()=>{$('#readingTimer').textContent=formatSeconds(Math.floor((Date.now()-readingStart)/1000))},1000)}
function updateQuestionProgress(){const answered=passage.questions.filter((_,i)=>$(`input[name="q${i}"]:checked`)).length;$('#questionProgress').textContent=`${answered} / ${passage.questions.length} 已作答`;$('#readingError').hidden=true}
function submitReading(){const answers=passage.questions.map((_,i)=>{const el=$(`input[name="q${i}"]:checked`);return el?Number(el.value):null});if(answers.some(a=>a===null)){$('#readingError').hidden=false;$('#readingError').scrollIntoView({behavior:'smooth',block:'center'});return}const score=answers.reduce((n,a,i)=>n+(a===passage.questions[i].answer?1:0),0);daily.reading={answers,score,total:passage.questions.length,seconds:Math.round((Date.now()-readingStart)/1000),completedAt:Date.now()};save();showReadingResult(false)}
function showReadingResult(restored){clearInterval(timerId);const r=daily.reading;passage.questions.forEach((q,i)=>{const section=$(`.question[data-question="${i}"]`),options=[...section.querySelectorAll('.option')];options.forEach((o,oi)=>{o.querySelector('input').disabled=true;if(oi===q.answer)o.classList.add('correct');if(oi===r.answers[i]&&oi!==q.answer)o.classList.add('wrong')});const chosen=section.querySelector(`input[value="${r.answers[i]}"]`);if(chosen)chosen.checked=true;section.querySelector('.explanation').hidden=false});$('#readingTimer').textContent=formatSeconds(r.seconds);updateQuestionProgress();$('#submitReading').hidden=true;const box=$('#readingResult');box.hidden=false;box.innerHTML=`<b>${r.score} / ${r.total} 题正确</b><p>${r.score===r.total?'定位准确，可以把注意力转向文中词汇。':r.score>=2?'整体理解不错，错题解析已标出关键信息。':'建议先对照解析重读相关段落，再进入词汇训练。'}</p><button class="primary-btn" id="startMemory">开始文中词汇多轮记忆</button>`;$('#startMemory').addEventListener('click',()=>startMemory(restored&&daily.rounds.length>0))}
function showWordPopover(button){const w=wordByName(button.dataset.word);if(!w)return;const p=$('#wordPopover');p.innerHTML=`<b>${w.word} ${w.pos}</b><span>${w.meaning}</span>`;const r=button.getBoundingClientRect();p.style.left=`${Math.min(innerWidth-275,Math.max(10,r.left))}px`;p.style.top=`${Math.min(innerHeight-100,r.bottom+8)}px`;p.hidden=false}

function setPhase(name){$$('.phase').forEach(p=>p.classList.toggle('active',p.id===`phase-${name}`));$$('.journey-step').forEach((b,i)=>{const order=['reading','memory','summary'],at=order.indexOf(name);b.classList.toggle('active',b.dataset.phase===name);b.classList.toggle('done',i<at)});window.scrollTo({top:0,behavior:'smooth'})}
function startMemory(resume=false){if(!daily.reading){toast('请先完成今日阅读');return}setPhase('memory');if(daily.summary&&resume){roundNo=daily.rounds.length+1;prepareRound()}else if(!roundQueue.length){roundNo=daily.rounds.length+1;prepareRound()}}
function dueWords(){return WORDS.filter(w=>state.progress[w.id]&&state.progress[w.id].due<=Date.now()&&!state.progress[w.id].mastered)}
function prepareRound(){const targetWords=passage.targets.map(wordByName).filter(Boolean);if(roundNo===1){const extras=dueWords().filter(w=>!passage.targets.includes(w.word)).slice(0,3);roundQueue=[...targetWords,...extras]}else{const last=daily.rounds.at(-1),rank={again:0,hard:1,good:2,easy:3};const names=(last?.ratings||[]).filter(x=>x.rating!=='easy').sort((a,b)=>rank[a.rating]-rank[b.rating]).map(x=>x.word);roundQueue=(names.length?names:passage.targets).map(wordByName).filter(Boolean)}wordIndex=0;roundRatings=[];$('#roundComplete').hidden=true;$('.memory-layout').hidden=false;renderWord()}
function contextFor(word){const sentence=passage.paragraphs.join(' ').match(new RegExp(`[^.!?]*\\b${escapeRx(word.word)}\\b[^.!?]*[.!?]`,'i'));return sentence?sentence[0].trim():word.example}
function renderWord(){const w=roundQueue[wordIndex];if(!w){completeRound();return}cardFlipped=false;memorySignalled=false;$('#wordCard').classList.remove('flipped');$('#memorySignal').disabled=true;$('#memorySignal').textContent='先点卡片理解单词';$('#ratingPanel').hidden=true;$('#roundLabel').textContent=`第 ${roundNo} 轮 · ${roundNo===1?'建立语境':'强化薄弱词'}`;$('#roundCounter').textContent=`${wordIndex+1} / ${roundQueue.length}`;$('#roundMeter').style.width=`${wordIndex/roundQueue.length*100}%`;$('#wordText').textContent=w.word;$('#wordPhonetic').textContent=w.phonetic;$('#wordPos').textContent=w.pos;$('#wordMeaning').textContent=w.meaning;$('#wordContext').textContent=contextFor(w);$('#wordCollocation').textContent=w.collocation;$('.source-chip').textContent=passage.targets.includes(w.word)?'来自今日阅读':'到期复习词';renderRoundBoard()}
function flipCard(){if(memorySignalled)return;cardFlipped=!cardFlipped;$('#wordCard').classList.toggle('flipped',cardFlipped);if(cardFlipped){$('#memorySignal').disabled=false;$('#memorySignal').textContent='这个词我记完了'}}
function signalMemory(){if(!cardFlipped||memorySignalled)return;memorySignalled=true;$('#memorySignal').hidden=true;$('#ratingPanel').hidden=false;$('#ratingPanel').scrollIntoView({behavior:'smooth',block:'nearest'})}
function scheduleRating(w,rating){const now=Date.now(),existing=state.progress[w.id],wasNew=!existing;let p=existing||{stage:-1,due:now,correct:0,wrong:0,seen:0,mastered:false},min;const advancedToday=p.last&&dayKey(p.last)===today;if(rating==='again'){p.stage=0;min=10;p.wrong++}else if(rating==='hard'){p.stage=Math.max(0,p.stage);min=Math.max(10,Math.round(INTERVALS[p.stage]*.6));p.correct++}else if(rating==='good'){if(!advancedToday)p.stage=Math.min(6,p.stage+1);else p.stage=Math.max(0,p.stage);min=INTERVALS[p.stage];p.correct++}else{if(!advancedToday)p.stage=Math.min(6,p.stage+2);else p.stage=Math.max(1,p.stage);min=INTERVALS[p.stage];p.correct++}p.seen++;p.last=now;p.due=now+min*60000;p.mastered=p.stage>=6&&rating!=='again';state.progress[w.id]=p;state.history.push({id:w.id,at:now,rating,wasNew,round:roundNo,passageId:passage.id});if(state.history.length>3000)state.history=state.history.slice(-3000);if(!state.activeDays.includes(today))state.activeDays.push(today)}
function rateWord(rating){if(!memorySignalled)return;const w=roundQueue[wordIndex];roundRatings.push({word:w.word,rating});scheduleRating(w,rating);save();wordIndex++;$('#memorySignal').hidden=false;renderWord();renderLibrary();renderReport()}
function renderRoundBoard(){const status=Object.fromEntries(roundRatings.map(x=>[x.word,x.rating])),labels={again:'忘了',hard:'模糊',good:'记住',easy:'太简单'};$('#roundWordList').innerHTML=roundQueue.map((w,i)=>`<div class="round-word ${i===wordIndex?'current':''} ${status[w.word]?'rated':''}"><b>${w.word}</b><span>${status[w.word]?labels[status[w.word]]:i===wordIndex?'正在学习':'待学习'}</span></div>`).join('')}
function completeRound(){daily.rounds.push({number:roundNo,completedAt:Date.now(),ratings:roundRatings});daily.summary=null;save();$('.memory-layout').hidden=true;const c={again:0,hard:0,good:0,easy:0};roundRatings.forEach(x=>c[x.rating]++);$('#roundStamp').textContent=`ROUND ${roundNo}`;$('#roundRecap').textContent=`忘了 ${c.again} · 模糊 ${c.hard} · 记住 ${c.good} · 太简单 ${c.easy}`;$('#roundComplete').hidden=false;$('#roundMeter').style.width='100%'}
function nextRound(){roundNo=daily.rounds.length+1;prepareRound();window.scrollTo({top:0,behavior:'smooth'})}
function finishToday(){if(!daily.rounds.length){toast('请至少完成一轮记忆');return}daily.completedAt=Date.now();daily.summary=buildSummary();save();renderSummary();setPhase('summary');renderReport()}
function buildSummary(){const r=daily.reading,all=daily.rounds.flatMap(x=>x.ratings),latest={};all.forEach(x=>latest[x.word]=x.rating);const vals=Object.values(latest),weight={again:0,hard:.45,good:.8,easy:1},wordRate=vals.length?vals.reduce((s,x)=>s+weight[x],0)/vals.length:0,readingRate=r.score/r.total,score=Math.round((readingRate*.45+wordRate*.55)*100),grade=score>=90?'A':score>=78?'B':score>=65?'C':'D',weak=Object.entries(latest).filter(([,x])=>x==='again'||x==='hard').map(([w])=>w),minutes=Math.max(1,Math.round((Date.now()-daily.startedAt)/60000));const advice=[];if(readingRate<.67)advice.push('明天先用 2 分钟回看今天的错题段落，练习用题干关键词定位原文证据。');else advice.push('阅读定位表现稳定，明天继续保持“先题干、后证据”的节奏。');if(weak.length)advice.push(`把 ${weak.slice(0,4).join('、')} 放在明早第一轮，先回想原文句子再看中文。`);else advice.push('今天没有明显薄弱词，明天优先做间隔到期复习，不必无效重复。');if(daily.rounds.length<2)advice.push('今天只完成 1 轮；若还有 5 分钟，建议立即再做一轮主动回想。');else advice.push(`你主动完成了 ${daily.rounds.length} 轮，今天到此即可，留出间隔比继续刷更多轮更有效。`);return{score,grade,readingRate,wordRate,weak,minutes,advice,createdAt:Date.now()}}
function renderSummary(){if(!daily.summary)return;const s=daily.summary;$('#summaryDate').textContent=`${today} · ${passage.title}`;$('#summaryGrade').textContent=s.grade;$('#summaryReading').textContent=`${Math.round(s.readingRate*100)}%`;$('#summaryRounds').textContent=daily.rounds.length;$('#summaryWords').textContent=new Set(daily.rounds.flatMap(r=>r.ratings.map(x=>x.word))).size;$('#summaryMinutes').textContent=s.minutes;$('#summaryHeadline').textContent=s.score>=90?'今天的理解与记忆都很扎实':s.score>=78?'今天完成得稳，少数词需要再加固':s.score>=65?'基础已建立，明天先处理薄弱点':'今天最重要的成果是找到了薄弱点';$('#assessmentText').textContent=`综合表现 ${s.score} 分。阅读正确率 ${Math.round(s.readingRate*100)}%，最后一轮词汇自评记忆率约 ${Math.round(s.wordRate*100)}%。${s.weak.length?'目前主要损耗来自部分词义回想不稳定，而不是学习量不足。':'文中核心词已形成较稳定的语境联系。'}`;$('#weakWords').innerHTML=s.weak.length?s.weak.map(w=>`<span class="weak-word">${w}</span>`).join(''):'<p>今天没有标记为“忘了”或“模糊”的词。</p>';$('#adviceList').innerHTML=s.advice.map(x=>`<li>${x}</li>`).join('')}

function renderLibrary(){const q=$('#wordSearch').value.trim().toLowerCase(),list=WORDS.filter(w=>(activeTopic==='全部'||w.topic===activeTopic)&&(!q||[w.word,w.meaning,w.collocation].join(' ').toLowerCase().includes(q)));$('#libraryCount').textContent=`共 ${WORDS.length} 个核心词 · 当前显示 ${list.length} 个`;$('#wordGrid').innerHTML=list.map(w=>{const p=state.progress[w.id],status=!p?['未学习','']:p.mastered?['已掌握','mastered']:['记忆中','learning'];return `<article class="word-item"><div class="row"><span>${w.topic}</span><span class="status-dot ${status[1]}">${status[0]}</span></div><h3>${w.word}</h3><p>${w.pos} ${w.meaning}</p><small>${w.collocation}</small></article>`}).join('')||'<div class="empty-state">没有找到匹配的词。</div>'}
function renderReport(){const ps=Object.values(state.progress),correct=ps.reduce((s,p)=>s+p.correct,0),total=ps.reduce((s,p)=>s+p.correct+p.wrong,0);$('#retentionRate').textContent=total?`${Math.round(correct/total*100)}%`:'—';const days=[];for(let i=6;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const k=dayKey(d);days.push({label:i===0?'今天':`${d.getMonth()+1}/${d.getDate()}`,count:state.history.filter(h=>dayKey(h.at)===k).length,today:i===0})}const max=Math.max(1,...days.map(d=>d.count));$('#weekBars').innerHTML=days.map(d=>`<div class="bar-col ${d.today?'today':''}" title="${d.count} 词次"><i style="height:${Math.max(4,d.count/max*160)}px"></i><small>${d.label}</small></div>`).join('');const counts=[0,0,0,0];ps.forEach(p=>{if(p.mastered)counts[3]++;else if(p.stage<=1)counts[0]++;else if(p.stage<=3)counts[1]++;else counts[2]++});$('#stageRows').innerHTML=['初识','加固','熟悉','掌握'].map((l,i)=>`<div class="stage-row"><div><span>${l}</span><b>${counts[i]}</b></div><i><b style="width:${ps.length?counts[i]/ps.length*100:0}%"></b></i></div>`).join('');const entries=Object.entries(state.daily).filter(([,d])=>d.summary).sort((a,b)=>b[0].localeCompare(a[0]));$('#dailyHistory').innerHTML=entries.length?entries.map(([date,d])=>{const p=READINGS.find(x=>x.id===d.passageId);return `<article class="history-item"><span>${date.slice(5)}</span><div><h3>${p?.title||'每日阅读'}</h3><p>阅读 ${Math.round(d.summary.readingRate*100)}% · ${d.rounds.length} 轮记忆 · ${d.summary.minutes} 分钟</p></div><b>${d.summary.grade}</b></article>`}).join(''):'<div class="empty-state">完成今天的阅读和单词记忆后，这里会出现第一份学习报告。</div>'}
function switchView(name){if(!['today','words','report','settings'].includes(name))name='today';$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$('#pageTitle').textContent={today:'今日训练',words:'高频词库',report:'学习报告',settings:'设置'}[name];history.replaceState(null,'',`#${name}`);if(name==='report')renderReport();if(name==='words')renderLibrary();window.scrollTo({top:0,behavior:'smooth'})}
function installApp(){if(deferredInstall){deferredInstall.prompt();deferredInstall.userChoice.finally(()=>deferredInstall=null);return}const isiOS=/iphone|ipad|ipod/i.test(navigator.userAgent);$('#installGuide').innerHTML=isiOS?'<ol><li>点击 Safari 底部“分享”。</li><li>选择“添加到主屏幕”。</li><li>点击右上角“添加”。</li></ol>':'<p>打开浏览器菜单，选择“安装应用”或“添加到主屏幕”。建议使用 Chrome、Edge 或 Safari。</p>';$('#installDialog').showModal()}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`拾词备份-${today}.json`;a.click();URL.revokeObjectURL(a.href);toast('学习记录已导出')}
function importData(file){const reader=new FileReader();reader.onload=()=>{try{const v=JSON.parse(reader.result);if(!v?.progress||!Array.isArray(v.history))throw new Error();state={...defaultState(),...v,daily:v.daily||{}};save();location.reload()}catch{toast('备份文件无法识别')}};reader.readAsText(file)}
function resetAll(){localStorage.removeItem(STORAGE_KEY);location.reload()}
function registerWebMCP(){const ctx=document.modelContext;if(!ctx?.registerTool)return;try{ctx.registerTool({name:'get_today_learning_status',title:'查看今日六级学习状态',description:'读取今日阅读成绩、已完成记忆轮数和学习建议。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>({reading:daily.reading?`${daily.reading.score}/${daily.reading.total}`:'not_completed',rounds:daily.rounds.length,completed:!!daily.summary,advice:daily.summary?.advice||[]})});ctx.registerTool({name:'complete_current_word_memory',title:'完成当前单词记忆并评级',description:'在用户已经理解当前单词后，记录 again、hard、good 或 easy 评级。',inputSchema:{type:'object',properties:{rating:{type:'string',enum:['again','hard','good','easy']}},required:['rating'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:input=>{if(!memorySignalled)throw new Error('用户尚未发出完成当前单词记忆的信号');const word=roundQueue[wordIndex]?.word;if(!word)throw new Error('当前没有待记忆单词');rateWord(input.rating);return{word,rating:input.rating,saved:true}}})}catch{}}

$('#submitReading').addEventListener('click',submitReading);$('#readAloudBtn').addEventListener('click',()=>speak(passage.paragraphs.join(' ')));$('#wordCard').addEventListener('click',flipCard);$('#speakWord').addEventListener('click',e=>{e.stopPropagation();speak(roundQueue[wordIndex]?.word||'')});$('#memorySignal').addEventListener('click',signalMemory);$$('.rating-row button').forEach(b=>b.addEventListener('click',()=>rateWord(b.dataset.rating)));$('#nextRound').addEventListener('click',nextRound);$('#finishToday').addEventListener('click',finishToday);$('#morePractice').addEventListener('click',()=>{roundNo=daily.rounds.length+1;setPhase('memory');prepareRound()});$$('[data-view]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));$$('.journey-step').forEach(b=>b.addEventListener('click',()=>{const p=b.dataset.phase;if(p==='reading')setPhase('reading');else if(p==='memory'&&daily.reading)startMemory(true);else if(p==='summary'&&daily.summary){renderSummary();setPhase('summary')}else toast(p==='memory'?'请先完成今日阅读':'完成阅读与至少一轮记忆后生成总结')}));$('#wordSearch').addEventListener('input',renderLibrary);$$('#topicFilters button').forEach(b=>b.addEventListener('click',()=>{activeTopic=b.dataset.topic;$$('#topicFilters button').forEach(x=>x.classList.toggle('active',x===b));renderLibrary()}));$('#installBtn').addEventListener('click',installApp);$('#installQuick').addEventListener('click',installApp);$('.dialog-close').addEventListener('click',()=>$('#installDialog').close());$('#exportBtn').addEventListener('click',exportData);$('#importBtn').addEventListener('click',()=>$('#importFile').click());$('#importFile').addEventListener('change',e=>e.target.files[0]&&importData(e.target.files[0]));$('#resetBtn').addEventListener('click',()=>$('#resetDialog').showModal());$('#cancelReset').addEventListener('click',()=>$('#resetDialog').close());$('#confirmReset').addEventListener('click',resetAll);window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e});document.addEventListener('click',e=>{if(!e.target.closest('.vocab-mark')&&!e.target.closest('#wordPopover'))$('#wordPopover').hidden=true});document.addEventListener('keydown',e=>{if(e.code==='Space'&&$('#phase-memory').classList.contains('active')){e.preventDefault();flipCard()}});
const now=new Date();$('#todayLabel').textContent=`${now.getFullYear()}年${now.getMonth()+1}月${now.getDate()}日 · ${['星期日','星期一','星期二','星期三','星期四','星期五','星期六'][now.getDay()]}`;renderPassage();renderLibrary();renderReport();if(daily.summary){renderSummary();setPhase('summary')}switchView(location.hash.slice(1)||'today');registerWebMCP();save();if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));

